### ISSUE TITLE
cannot find directories: GL/glew and GLFW/glfw3.h

### ISSUE THREAD

**Issue by fantasmashy** [flathub/io.qt.QtCreator#147]
It doesn't found it even with the file address.
it works in the non-flathub version.

**Comment by marbub** [comment]
The flatpak accesses the /usr in runtime. To access it outside the sandbox, we need upstream support, which we can provide inside the SDK.

**Comment by marbub** [comment]
Wen can add https://github.com/flathub/shared-modules/tree/master/glew to the manifest.

**Comment by marbub** [comment]
Adding https://github.com/flathub/shared-modules/tree/master/glew doesn't work because it is removing the header files. 

@bbhtt  told me, that will not be changed too: https://github.com/flathub/shared-modules/issues/306

I could now maintain them in the application, but then I have to do that for every possible library. That maintenance burden is too high. 

So the only solution would be not to use flatpak. Sorry.
