### ISSUE TITLE
Use org.kde.Sdk/6.2 so you don't need to build Qt all the time?

### ISSUE THREAD

**Issue by tsdgeos** [flathub/io.qt.QtCreator#40]
Do you think it would make sense to use the org.kde.Sdk/6.2 instead of building Qt inside this flatpak?

Would help with build times and we can share any potential problem in packaging Qt instead of having to do things twice

The code for that runtime can be found at Sdk https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/qt6.2/org.kde.Sdk.json.in

**Comment by 4c0n** [comment]
Hi thanks for reaching out 😊, the thing is, that the sdk platform does not include all the modules and on top of that I'd like the flatpak to support both Qt 5 and 6, and also the android builds, and python bindings in order to provide a turn-key solution for Qt development that can be used to maintain existing Qt 5 apps and develop new Qt 6 apps.

Currently we're kind of misusing the Sdk runtime as a platform to provide Qt 5.

What would make more sense to me is to split off the Qt modules into extensions so that they can be re-used much more easily, similar to for example openjdk and nodejs to name a few. There are others on the forum noting that would be easier for them as well.
That way the extensions could be used to install Qt support (multiple versions) on the platform for apps and they could be used in the Sdk to provide the current functionality.

Of course I'd be more than happy to collaborate on this in some way ❤️

**Comment by tsdgeos** [comment]
Ah, you want to build for Qt5 and Qt6, i see, that's kind of a special use case i guess, not sure we can help from a runtime point of view.

Closing this then
