### ISSUE TITLE
running on Wayland crashes GNOME Shell 3.36

### ISSUE THREAD

**Issue by christian-rauch** [flathub/io.qt.QtCreator#48]
As soon as I call `flatpak run io.qt.QtCreator`, my desktop (GNOME Shell 3.36.9, Wayland) crashes and I have to login again.

**Comment by 4c0n** [comment]
Did you check your system log? Maybe it lists the actual error, in any case it works fine on Gnome and Wayland for me. I'm using Gnome 4.1 so perhaps you could try upgrading your system. I sincerely doubt it has something to do with the flatpak itself.

**Comment by christian-rauch** [comment]
Well, that's a known issue in the compositor that has been fixed in newer versions. But you cannot just upgrade GNOME on Ubuntu 20.04 LTS.

The flatpak cannot "fix" the issue. You can only work around this by blocking Wayland for the time being. I just opened the issue so others do not try to use it on Wayland since it crashes the entire desktop and all unsaved work will be gone.

**Comment by 4c0n** [comment]
Or by upgrading to a newer Ubuntu version I might add. Although you wouldn't be on an LTS version, which are not great for software development anyway IMO.

**Comment by 4c0n** [comment]
Could you change the issue title to something more specific? Currently it looks like it won't run on any version, while actually that's not the case at all.

**Comment by 4c0n** [comment]
Also, if there's nothing to be fixed here, I'm not sure how long to keep this issue open...
Perhaps it would be better to put this information in some sort of "known problems" issue or file?

**Comment by christian-rauch** [comment]
Upgrading the Ubuntu version is out of question. It would break more things than it would fix.

I think this is a critical issue (not with Qt Creator per se) as it will crash the entire desktop and close all programs without the ability to save. I would either implement the X11 workaround (prevent Wayland connections) or keep this open so it is clear that someone should not use this on GNOME Shell 3.36.

**Comment by 4c0n** [comment]
> Upgrading the Ubuntu version is out of question. It would break more things than it would fix.

You can't keep running the same old version forever anyway.

> I think this is a critical issue (not with Qt Creator per se) as it will crash the entire desktop and close all programs without the ability to save. I would either implement the X11 workaround (prevent Wayland connections) or keep this open so it is clear that someone should not use this on GNOME Shell 3.36.

Which version has a fix for this problem? And will Ubuntu eventually distribute that version? The latest shell version 3.38, does that fix it? 

I'm not going to disable Wayland support. But honestly, I don't think anyone will check out this issue before installing the Flatpak and running into the problem.

Keeping the issue open forever also does not seem like a good idea to me, as we would end up having an issue open for every platform specific problem and just accumulating them will not solve anything. If anything maybe a patch for the appdata file might be better, so that the information would show up on: https://flathub.org/apps/details/io.qt.QtCreator and the software store tools.

Another solution could be a patch for the Qt Creator startup script that somehow checks if the problem would manifest and exit gracefully in that case for example. However, preferably these patches would be implemented upstream in the actual Qt Creator repositories IMO. Although I doubt that they would accept them, as they're very much workarounds for a problem that exists in Gnome + Wayland.

**Comment by christian-rauch** [comment]
> You can't keep running the same old version forever anyway.

You probably don't want either of the extremes (oldest or latest software). There is a reason why there are long-term supported Linux distributions. You cannot just update distributions to intermediate versions and break workflows.

> Which version has a fix for this problem? And will Ubuntu eventually distribute that version? The latest shell version 3.38, does that fix it?

I cannot point to the fix right now, but the latest version 41 will have that fix. However, users of Ubuntu 20.04 LTS will have to stick with 3.36 until they update to 22.04.

> Keeping the issue open forever also does not seem like a good idea to me

There is still the workaround (blocking Wayland connections) that I mentioned a couple of times now.

> Another solution could be a patch for the Qt Creator startup script that somehow checks if the problem would manifest and exit gracefully in that case for example.

I still think that blocking Wayland connections and using X11 instead is the better option.

> However, preferably these patches would be implemented upstream in the actual Qt Creator repositories IMO. Although I doubt that they would accept them, as they're very much workarounds for a problem that exists in Gnome + Wayland.

I doubt that too. Whatever causes this issue, it is not the fault of the toolkit. It is indeed a compositor issue that has been fixed already.

This issue is just about making sure that people don't use this on Wayland with GNOME Shell 3.36 or adding a workaround that blocks the Wayland connection and always uses X11 until GNOME Shell 3.36 is not in major use any more.

**Comment by 4c0n** [comment]
Looks like we disagree on some things. The only things that you did not address are the fact that users are not going to look at this issue before running into the problem (where I'm from we'd call that "serving the mustard after the meal") and introducing a patch to get information about the problem displayed in the application description (so that people can see it before installing it).

As a maintainer I feel that an issue should be solvable and thus should have some sort of task or action. Considering that Ubuntu LTS versions are supported for 5 years, it is not inconceivable that people will continue to use it after the release of 22.04 and I don't feel that disabling Wayland support for that long is an adequate response in this case. You can repeat yourself as many times as you like, but that will not change my mind.

Breaking this down:
- What is the timeline? (When is the problem resolved)
- I suppose it would be nice to inform users about this potential problem, if so where do we refer them to for more information about it?

**Comment by christian-rauch** [comment]
> You can repeat yourself as many times as you like, but that will not change my mind.

Sorry for repeating myself, but you never responded to my "prevent Wayland connection before. I thought you just overlooked it.

> The only things that you did not address are the fact that users are not going to look at this issue

The issue is here so that other measures could be taken. Some options were mentioning this as "known issue" in the README, AppData, or somehow with a GUI-dialog in the startup-script. Once this has been addressed, the issue can be closed of course.

Patching the startup script to check for a Wayland connection and the GNOME Shell version will prevent the desktop from crashing, but it will also mean that this flatpak will not be usable.
